__inherits__: ../../api/method.yaml
functionality:
  name: "logistic_regression"
  namespace: "label_projection/methods"
  version: "dev"
  description: "Applied Logistic Regression"
  info:
    type: method
    label: Logistic Regression
  arguments:
    - name: "--max_iter"
      type: "integer"
      example: "100"
      description: "Maximum number of iterations"
      required: true
  resources:
    - type: python_script
      path: script.py
    - path: "../../utils.py"
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - scprep
          - sklearn
          - "anndata<0.8"
  - type: native
  - type: nextflow
