# use metric api spec
__merge__: ../../api/comp_metric.yaml
functionality:
  name: cell_cycle_conservation
  namespace: batch_integration/embedding/metrics
  description: Cell cycle conservation score based on cell cycle gene scoring
  arguments:
    - name: --organism
      type: string
      description: Name of organism to compute cell cycle scores on
      required: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: pyyaml
  - type: nextflow
