functionality:
  name: pancreas
  namespace: batch_integration/datasets
  version: dev
  description: Preprocess adata object for data integration
  authors:
    - name: Michaela Mueller
      roles: [ maintainer, author ]
      props: { github: mumichae }
  arguments:
    - name: --output
      alternatives: [ -o ]
      type: file
      direction: output
      description: Output h5ad file of the cleaned dataset
      required: true
    - name: --adata
      type: file
      description: Anndata HDF5 file
      required: true
    - name: --label
      type: string
      description: Cell annotation label in adata.obs
      required: true
    - name: --batch
      type: string
      description: Batch assignment in adata.obs
      required: true
    - name: --hvgs
      type: integer
      description: Number of highly variable genes
      default: 2000
      required: false
    - name: --debug
      type: boolean
      description: Verbose output for debugging
      default: False
      required: false
  resources:
    - type: python_script
      path: script.py
    - path: "../utils.py"
  tests:
    - type: python_script
      path: test.py
    - path: '../resources/data_loader_pancreas.h5ad'
platforms:
  - type: docker
    image: mumichae/scanpy-r-micromamba:0.1.1
    setup:
      - type: docker
        run:
          - ls -la
          - micromamba install -y -c conda-forge -c bioconda scprep bioconductor-scran
#          - micromamba install -y -n base -f /root/env.yaml
          - micromamba clean --all --yes
#        resources:
#          - envs/py_r.yaml /root/env.yaml
  - type: native
  - type: nextflow
