functionality:
  name: "optical_screen"
  namespace: "datasets/loaders"
  description: "Optical screen"
  arguments:
    - name: "--output"
      __merge__: ../../api/file_raw.yaml
      direction: "output"
  resources:
    - type: python_script
      path: script.py
    - path: ../../../../resources/OPTICAL_Secondary_processed.csv
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        pypi:
          - anndata~=0.8.0
          - scanpy
          - pandas
  - type: nextflow