type: file
description: "Solution (complete data)"
example: "TODO"
info:
  label: Solution
  slots:
    uns:
      - type: list
        name: phenotypes
        description: "A list of phenotype names in layers"
        required: true
