__inherits__: ../../api/method.yaml
functionality:
  name: "mlp"
  namespace: "label_projection/methods"
  version: "dev"
  description: "Multilayer perceptron"
  info:
    type: method
    label: Multilayer perceptron
  arguments:
    - name: "--hidden_layer_sizes"
      type: "integer"
      multiple: true
      description: "The ith element represents the number of neurons in the ith hidden layer."
      required: true
    - name: "--max_iter"
      type: "integer"
      example: "100"
      description: "Maximum number of iterations"
      required: true
  resources:
    - type: python_script
      path: script.py
    - path: "../../utils.py"
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - sklearn
          - "anndata<0.8"
  - type: nextflow
