# use metric api spec
__merge__: ../../api/comp_metric.yaml
functionality:
  name: pcr
  namespace: batch_integration/embedding/metrics
  description: PCA regression
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: pyyaml
  - type: nextflow
