type: file
description: "The masked spatial data file"
example: "resources_test/spatial_decomposition/pancreas/anndata_spatial_masked.h5ad"
info:
  short_description: "Masked spatial data"
  slots:
    layers: 
      - type: integer
        name: counts
        description: Raw counts
    obsm:
      - type: float
        name: coordinates
        description: XY coordinates for each spot
    uns:
      - type: string
        name: cell_type_names
        description: Cell type names corresponding to columns of `proportions` in output
      - type: string
        name: dataset_id
        description: "A unique identifier for the dataset"