# use metric api spec
__merge__: ../../../api/comp_metric.yaml
functionality:
  name: asw_batch
  namespace: batch_integration/embedding/metrics
  description: Average silhouette of batches per label
  info:
    output_type: embedding
    integrated_embedding: X_emb
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: pyyaml
  - type: nextflow
