# use metric api spec
__merge__: ../../../api/comp_metric.yaml
functionality:
  name: asw_batch
  namespace: batch_integration/embedding/metrics
  version: dev
  description: Average silhouette of batches per label
  authors:
    - name: Michaela Mueller
      roles: [ maintainer, author ]
      props: { github: mumichae }
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../../../resources_test/batch_integration/embedding/methods/combat.h5ad
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
  - type: nextflow
