# use method api spec
__merge__: ../../../api/comp_method.yaml
functionality:
  name: combat
  namespace: batch_integration/graph/methods
  version: dev
  description: Run Combat
  authors:
    - name: Michaela Mueller
      roles: [ maintainer, author ]
      props: { github: mumichae }
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../../../resources_test/batch_integration/pancreas/processed.h5ad
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
  - type: nextflow
