functionality:
  name: "run_benchmark"
  namespace: "dimensionality_reduction/workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          type: "string"
          description: "The ID of the normalized dataset"
          required: true
        - name: "--dataset_id"
          type: "string"
          description: "The ID of the dataset"
          required: true
        - name: "--input"
          type: "file" # todo: replace with includes
    - name: Outputs
      arguments:
        - name: "--output"
          direction: "output"
          type: file
          example: output.tsv
  resources:
    - type: nextflow_script
      path: main.nf
  # test_resources:
  #   - type: nextflow_script
  #     path: main.nf
  #     entrypoint: test_wf
platforms:
  - type: nextflow