__inherits__: ../../api/comp_method.yaml
functionality:
  name: "baseline"
  namespace: "denoising/methods"
  description: "baseline"
  info:
    type: method
    label: baseline
    # paper_name: "Molecular Cross-Validation for Single-Cell RNA-seq""
    # paper_url: "https://doi.org/10.1101/786269"
    # paper_year: 2019
    paper_doi: "10.1101/786269"
    code_url: "https://github.com/czbiohub/molecular-cross-validation"
    v1_url: /openproblems/tasks/denoising/methods/baseline.py
    v1_commit: f24fb718b1115ca85130a45f2e56fddb00075d22
  arguments:
    - name: "--layer_input"
      type: string
      default: "denoised"
      description: "Which layer to use as input."
    - name: "--baseline"
      type: "string"
      required: true
      choices: ["no_denoising", "perfect_denoising"]
      description: "wich baseline needs to be created"
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
  - type: nextflow
