# use metric api spec
__merge__: ../../../api/comp_metric.yaml
functionality:
  name: ari
  namespace: batch_integration/graph/metrics
  version: dev
  description: Adjusted rand index (ARI)
  authors:
    - name: Michaela Mueller
      roles: [ maintainer, author ]
      props: { github: mumichae }
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../../../resources_test/batch_integration/graph/methods/bbknn.h5ad
    - type: python_script
      path: test_combat.py
    - path: ../../../../../resources_test/batch_integration/graph/methods/combat.h5ad
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
  - type: nextflow
