functionality:
  name: bbknn
  namespace: batch_integration/graph/methods
  version: dev
  description: Run BBKNN on adata object
  authors:
    - name: Michaela Mueller
      roles: [ maintainer, author ]
      props: { github: mumichae }
  arguments:
    - name: --output
      alternatives: [ -o ]
      type: file
      direction: output
      description: Anndata HDF5 file of the integrated graph in adata.obsp['connectivities']
      required: true
    - name: --adata
      type: file
      description: Unintegrated anndata HDF5 file
      required: true
    - name: --hvg
      type: integer
      description: |
        Number of highly variable genes to select by.
        If 0, no HVG selection will be performed.
      required: true
    - name: --scaling
      type: boolean
      description: Whether to scale the data or not
      required: true
    - name: --debug
      type: boolean
      description: Verbose output for debugging
      default: false
      required: false
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - type: python_script
      path: test_scaled_hvg.py
    - path: '../../../resources/datasets_pancreas.h5ad'
platforms:
  - type: docker
    image: mumichae/scib-base:0.1
    setup:
      - type: python
        packages:
          - bbknn
  - type: native
  - type: nextflow
