__merge__: ../../api/comp_method.yaml
functionality:
  name: "phate"
  namespace: "dimensionality_reduction/methods"
  description: "Potential of heat-diffusion for affinity-based transition embedding"
  info:
    type: method
    label: PHATE
    paper_doi: "10.1038/s41587-019-0336-3"
    code_url: https://github.com/KrishnaswamyLab/PHATE/
    v1_url: openproblems/tasks/dimensionality_reduction/methods/phate.py
    v1_commit: a796e02e13a43e8861b124edbb9d287f162d4a14
    preferred_normalization: sqrt_cpm
    variants:
      phate_default:
      phate_sqrt:
        gamma: 0
      phate_logCPM_1kHVG:
        preferred_normalization: log_cpm
  arguments:
    - name: '--n_pca'
      type: integer
      default: 50
      description: Number of principal components of PCA to use.
    - name: '--g0'
      type: boolean_true
      description: Set informational distance constant to 0.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
          - phate==1.0.*
          - scprep
          - pyyaml
          - "scikit-learn<1.2"
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
