__inherits__: ../../api/comp_method.yaml
functionality:
  status: disabled
  name: "dca"
  namespace: "denoising/methods"
  description: "Deep Count Autoencoder"
  info:
    type: method
    label: DCA
    # paper_name: "Single-cell RNA-seq denoising using a deep count autoencoder""
    # paper_url: "https://www.nature.com/articles/s41467-018-07931-2"
    # paper_year: 2019
    paper_doi: "0.1038/s41467-018-07931-2"
    code_url: "https://github.com/theislab/dca"
    v1_url: /openproblems/tasks/denoising/methods/dca.py
    v1_commit: 903469a532b96b25ef7d727e687c5b4263966323
  arguments:
    - name: "--layer_input"
      type: string
      default: "counts"
      description: Which layer to use as input.
    - name: "--epochs"
      type: "integer"
      default: 300
      description: "Number of total epochs in training"
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
          - dca==0.3.4
  - type: nextflow
