__inherits__: ../../api/comp_method.yaml
functionality:
  name: "dca"
  namespace: "denoising/methods"
  description: "Deep Count Autoencoder"
  info:
    type: method
    label: DCA
    # paper_name: "Single-cell RNA-seq denoising using a deep count autoencoder""
    # paper_url: "https://www.nature.com/articles/s41467-018-07931-2"
    # paper_year: 2019
    paper_doi: "10.1038/s41467-018-07931-2"
    code_url: "https://github.com/theislab/dca"
    v1_url: /openproblems/tasks/denoising/methods/dca.py
    v1_commit: c2470ce02e6f196267cec1c554ba7ae389c0956a
    preferred_normalization: counts
  arguments:
    - name: "--epochs"
      type: "integer"
      default: 300
      description: "Number of total epochs in training"
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: "python:3.7"
    setup:
      - type: python
        packages:
          - anndata<0.8
          - dca==0.3.4
          - keras>=2.4,<2.11
          - tensorflow==2.4.3
          - protobuf==3.20.*
          - scipy
  - type: nextflow
    directives: 
      label: [ midmem, midcpu ]
