# use method api spec
__merge__: ../../../api/comp_method.yaml
functionality:
  name: combat
  namespace: batch_integration/embedding/methods
  description: Run Combat
  info:
    output_type: embedding
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../../../resources_test/batch_integration/pancreas/unintegrated.h5ad
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: [ pyyaml ]
  - type: nextflow
