__inherits__: ../../api/comp_metric.yaml
functionality:
  name: ""
  namespace: "dimensionality_reduction/metrics"
  description: ""
  info:
    v1_url: openproblems/tasks/dimensionality_reduction/metrics/density.py 
    v1_commit: c2470ce02e6f196267cec1c554ba7ae389c0956a
    metrics:
      - id: 
        label: 
        description: 
        min: 0
        max: -1
        minimize: true
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../../resources_test/common/pancreas/
      dest: input
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - scipy
          - numpy
          - "anndata>=0.8"
          - typing
          - umap
  - type: nextflow