__merge__: ../api/comp_split_dataset.yaml
functionality:
  name: "split_dataset"
  namespace: "dimensionality_reduction"
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/common/pancreas/
      dest: input
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - pyyaml
          - "anndata>=0.8"
  - type: nextflow
