# use method api spec
__merge__: ../../api/comp_method_graph.yaml
functionality:
  name: embed_to_graph
  namespace: batch_integration/methods_graph
  description: "Transform an embedded integration to a graph integration"
  info:
    type: method
    method_name: Embedding to Graph
    variants:
      embed_to_graph:
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        pypi:
          - scanpy
          - pyyaml
  - type: nextflow
