functionality:
  name: "get_metric_info"
  namespace: "common"
  description: "Extract metric info"
  arguments:
    - name: "--input"
      type: "file"
      multiple: true
      example: src/label_projection
      description: "A task dir"
    - name: "--output"
      type: "file"
      direction: "output"
      default: "output.yaml"
      description: "Output yaml"
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: r
        cran: [ anndata, tidyverse ]
      - type: apt
        packages: [ libhdf5-dev, libgeos-dev, python3, python3-pip, python3-dev, python-is-python3 ]
      - type: python
        pip: [ anndata>=0.8 ]
  - type: nextflow
