__inherits__: ../../api/method.yaml
functionality:
  name: "knn_classifier"
  namespace: "label_projection/methods"
  version: "dev"
  description: "Nearest neighbor pattern classification"
  info:
    type: method
    label: KNN
  resources:
    - type: python_script
      path: script.py
    - path: "../../utils.py"
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - scprep
          - sklearn
          - "anndata<0.8"
  - type: nextflow
