__merge__: ../api/get_info.yaml
functionality:
  name: "get_method_info"
  namespace: "common"
  description: "Extract method info"
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: r
        cran: [ tidyverse ]
      - type: apt
        packages: [ curl, default-jdk ]
      - type: docker
        run: "curl -fsSL get.viash.io | bash -s -- --bin /usr/local/bin/"
    test_setup:
      - type: apt
        packages: [libhdf5-dev, libgeos-dev, python3, python3-pip, python3-dev, python-is-python3, git]
      - type: docker
        run: "git clone https://github.com/openproblems-bio/openproblems-v2.git"
  - type: nextflow
  - type: native
