functionality:
  name: "get_method_info"
  namespace: "common"
  description: "Extract method info"
  arguments:
    - name: "--input"
      type: "file"
      multiple: true
      example: src/label_projection
      description: "A task dir"
    - name: "--output"
      type: "file"
      direction: "output"
      default: "output.json"
      description: "Output json"
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: r
        cran: [ tidyverse ]
      - type: docker
        run: "curl -fsSL get.viash.io | bash -s -- --bin /usr/local/bin"
  - type: nextflow
