__inherits__: ../../api/comp_method.yaml
functionality:
  name: "magic"
  namespace: "denoising/methods"
  description: "MAGIC: Markov affinity-based graph imputation of cells"
  info:
    type: method
    label: magic
    # paper_name: "Recovering Gene Interactions from Single-Cell Data using Data Diffusion"
    # paper_url: "https://doi.org/10.1016/j.cell.2018.05.061"
    # paper_year: 2018
    paper_doi: "10.1016/j.cell.2018.05.061"
    code_url: "https://github.com/KrishnaswamyLab/MAGIC"
    v1_url: /openproblems/tasks/denoising/methods/magic.py
    v1_commit: 2fbc2d4c8d3ff955ea948fc082635cf779b1927e
  arguments:
    - name: "--layer_input"
      type: string
      default: "counts"
      description: Which layer to use as input.
    - name: "--solver"
      type: "string"
      choices: ["exact", "approximate"]
      default: "exact"
      description: Which solver to use.
      required: true
    - name: "--norm"
      type: string
      required: true
      choices: ["sqrt", "log"]
      default: "sqrt"
      description: Normalization method
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
          - scprep
          - magic-impute
  - type: nextflow
