functionality:
  name: "random_labels"
  namespace: "label_projection/control_methods"
  version: "dev"
  description: "Random Labels dummy"
  info:
    type: negative_control
    label: Random prediction
  authors:
    - name: "Nikolay Markov"
      roles: [ author, maintainer ]
      props: { github: mxposed }
  arguments:
    - name: "--input"
      type: "file"
      description: "Input data to predict"
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      description: "Ouput data containing predictions"
      direction: "output"
      example: "output.mv.h5ad"
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test_script.py
    - type: file
      path: "../../../../resources_test/label_projection/pancreas/toy_preprocessed_data.h5ad"
platforms:
  - type: native
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scanpy
          - "anndata<0.8"
  - type: nextflow
