# use method api spec
__merge__: ../../api/comp_method_feature.yaml
functionality:
  name: feature_to_embed
  description: "Transform a feature integration to an embedded integration"
  info:
    type: method
    method_name: Feature to Embed
    preferred_normalization: log_cpm
    variants:
      feature_to_embed:
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        pypi: 
          - pyyaml
          - scanpy
  - type: nextflow
