__inherits__: ../../api/comp_method.yaml
functionality:
  name: "scanvi"
  namespace: "label_projection/methods"
  description: |
    Probabilistic harmonization and annotation of single-cell 
    transcriptomics data with deep generative models.
  info:
    type: method
    label: scANVI
    paper_doi: "10.1101/2020.07.16.205997"
    code_url: "https://github.com/YosefLab/scvi-tools"
  arguments:
    - name: "--hvg"
      type: boolean
      default: true
      description: "Whether or not to reduce the input matrix to the set of HVG genes before training the model."
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:22.09-py3
    setup:
      - type: python
        packages: 
          - "anndata>=0.8"
          - scvi-tools
    # image: "python:3.10"
    # setup:
    #   - type: python
    #     packages:
    #       - "anndata>=0.8"
    #       - scvi-tools
  - type: nextflow
    directives: 
      label: [ midmem, highcpu, gpu ]
