# use method api spec
__merge__: ../../api/comp_method_graph.yaml
functionality:
  name: bbknn
  description: "BBKNN: fast batch alignment of single cell transcriptomes"
  info:
    type: method
    method_name: BBKNN
    paper_reference: "polanski2020bbknn"
    code_url: https://github.com/Teichlab/bbknn
    # v1_url: openproblems/tasks/xxxxxx/methods/xxxxxx.py
    # v1_commit: xxxxxxxxxxxxxx
    # preferred_normalization: log_cpm
    # variants:
    #   bbknn:
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi:
          - bbknn
          - pyyaml
  - type: nextflow
