__merge__: ../../api/comp_method.yaml
functionality:
  name: "densmap"
  namespace: "dimensionality_reduction/methods"
  description: "density-preserving based on UMAP"
  info:
    type: method
    label: densMAP
    paper_doi: "10.1038/s41587-020-00801-7"
    code_url: https://github.com/lmcinnes/umap
    v1_url: openproblems/tasks/dimensionality_reduction/methods/densmap.py
    v1_comp_id: "densMAP PCA (logCPM, 1kHVG)"
    v1_commit: a796e02e13a43e8861b124edbb9d287f162d4a14
    preferred_normalization: log_cpm
  arguments:
    - name: "--no_pca"
      type: boolean_true
      description: Do not apply PCA with 50 dimensions before running UMAP.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - scanpy
          - "anndata>=0.8"
          - pyyaml
          - umap-learn
  - type: nextflow
    directives: 
      label: [ highmem, highcpu ]
