functionality:
  name: "citeseq_cbmc"
  namespace: "modality_alignment/datasets"
  version: "dev"
  description: "CITE-seq Cord Blood Mononuclear Cells"
  info:
    accession_id: "GSE100866"
    doi: "10.1038/nmeth.4380"
    organism: "human"
    cell_types: "CL:2000001" # peripheral blood mononuclear cells
    technology: "dropseq"
  arguments:
    - name: "--id"
      type: "string"
      default: "citeseq_cbmc"
      description: "The id of the output dataset id"
    - name: "--input1"
      type: "file"
      default: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE100866&format=file&file=GSE100866%5FCBMC%5F8K%5F13AB%5F10X%2DRNA%5Fumi%2Ecsv%2Egz"
      description: "Path or URL to the RNA counts as a gzipped csv file."
    - name: "--input2"
      type: "file"
      default: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE100866&format=file&file=GSE100866%5FCBMC%5F8K%5F13AB%5F10X%2DADT%5Fumi%2Ecsv%2Egz"
      description: "Path or URL to the ADT counts as a gzipped csv file."
    - name: "--test"
      type: "boolean_true"
      description: "Subset the dataset"
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      default: "output.h5ad"
      description: "Output h5ad file containing both RNA and ADT data"
  resources:
    - type: python_script
      path: ./script.py
    - path: "../../resources/utils.py"
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scprep
          - anndata # needed by utils.py
          - pandas # needed by utils.py
          - scanpy # needed by utils.py
          - numpy # needed by utils.py
  - type: nextflow
