functionality:
  name: "pancreas_dataset"
  namespace: "label_projections/datasets"
  version: "dev"
  description: "Pancreas datasets for label_projection tasks"
  authors:
    - name: "Scott Gigante"
      roles: [ maintainer, author ]
      props: { github: scottgigante }
  arguments:
    - name: "--dataset-type"
      alternatives: ["-dt"]
      type: "string"
      description: "The dataset type that should used to get data"
      required: true
    # - name: "--output"
    #   alternatives: ["-o"]
    #   type: "file"
    #   direction: "output"
    #   default: "output.h5ad"
    #   description: "Output h5ad file containing both input matrices data"
    #   required: true
  resources:
    - type: python_script
      path: pancreas.py
    # - path: "../../utils/utils.py"
  # tests:
  #   - type: python_script
  #     path: test.py
platforms:
  - type: native
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        packages:
          - scprep
          - anndata # needed by utils.py
          - pandas # needed by utils.py
          - scanpy # needed by utils.py
          - numpy # needed by utils.py
  - type: nextflow
