# use method api spec
__merge__: ../../api/comp_method_graph.yaml
functionality:
  name: scanorama_embed
  description: Run Scanorama on adata object, use embedding output
  info:
    type: method
    output_type: graph
    method_name: Scanorama
    # paper_reference: "xxxxxxxxxxx"
    # code_url: xxxxxxxxxxx
    # v1_url: openproblems/tasks/xxxxxx/methods/xxxxxx.py
    # v1_commit: xxxxxxxxxxxxxx
    # preferred_normalization: log_cpm
    # variants:
    #   combat:
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi:
          - scanorama
          - pyyaml
  - type: nextflow
