functionality:
  name: "test_comp"
  version: 0.0.1
  description: |
    Replace this with a (multiline) description of your component.
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Describe the input file.
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Describe the output file.
    - name: "--option"
      type: string
      description: Describe an optional parameter.
      default: "default-"
  resources:
    - type: bash_script
      path: script.sh
  tests:
    - type: bash_script
      path: test.sh
platforms:
  - type: docker
    image: ubuntu:20.04
    setup:
      - type: apt
        packages: 
          - bash
  - type: native
  - type: nextflow
