# use method api spec
__merge__: ../../api/comp_method_embedding.yaml
functionality:
  name: combat
  namespace: batch_integration/methods_embedding
  description: Run Combat
  info:
    type: method
    method_name: Combat
    paper_refernce: hansen2012removing
    v1_url:
    v1 commit:
    variants:
      combat:
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.2
    setup:
      - type: python
        pypi: [ pyyaml ]
  - type: nextflow
