# use method api spec
__merge__: ../../api/comp_method_feature.yaml
functionality:
  name: mnn
  info:
    label: MNN
    summary: "TODO"
    description: |
      "TODO"
    reference: "hie2019efficient"
    repository_url: "https://github.com/brianhie/scanorama"
    documentation_url: "https://github.com/brianhie/scanorama#readme"
    v1:
      path: openproblems/tasks/_batch_integration/batch_integration_graph/methods/scanorama.py
      commit: 29803b95c88b4ec5921df2eec7111fd5d1a95daf
    preferred_normalization: log_cpm
    variants:
      mnn_full_unscaled:
      mnn_hvg_unscaled:
        hvg: true
      mnn_hvg_scaled:
        hvg: true
        preferred_normalization: log_cpm_scaled
      mnn_full_scaled:
        preferred_normalization: log_cpm_scaled
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.0
    setup:
      - type: apt
        packages: [ gcc-8 ]
      - type: python
        pypi:
          - mnnpy
          - scanpy
          - scib==1.1.3
  - type: nextflow
