functionality:
  name: "mlp_scran"
  namespace: "label_projection/methods/mlp"
  version: "dev"
  description: ""
  authors:
    - name: "Scott Gigante"
      roles: [ author ]
      props: { github: scottgigante }
    - name: "Vinicius Chagas"
      roles: [ maintainer ]
      props: { github: chagasVinicius }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "input.h5ad"
      description: "Input file that will be used to generate predictions"
      required: true
    - name: "--hidden_layer_sizes"
      type: "integer"
      multiple: true
      description: "The ith element represents the number of neurons in the ith hidden layer."
    - name: "--max_iter"
      type: "integer"
      example: "100"
      description: "Maximum number of iterations"
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "Output data labeled"
      required: true
  resources:
    - type: python_script
      path: script.py
    - path: "../../../../common/tools/normalize.py"
    - path: "../../../utils.py"
  tests:
    - type: python_script
      path: test_script.py
    - type: file
      path: "../../../resources/pancreas/toy_preprocessed_data.h5ad"
platforms:
  - type: docker
    image: "singlecellopenproblems/openproblems-r-base:latest"
    setup:
      - type: r
        bioc:
          - scran
          - BiocParallel
      - type: python
        packages:
          - scanpy
          - scprep
          - sklearn
          - "anndata<0.8"
  - type: nextflow
