name: main build

on:
  push:
    branches: [ 'main' ]

jobs:
  # phase 1
  list_components:
    env:
      s3_bucket: s3://openproblems-data/resources_test/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: viash-io/viash-actions/setup@v2

    # create cachehash key
    - name: Create hash key
      id: cachehash
      run: |
        AWS_EC2_METADATA_DISABLED=true aws s3 ls $s3_bucket --recursive --no-sign-request > bucket-contents.txt
        echo "cachehash=resources_test__$( md5sum bucket-contents.txt | awk '{ print $1 }' )" >> $GITHUB_OUTPUT
    
    # initialize cache
    - name: Cache resources data
      uses: actions/cache@v3
      with:
        path: resources_test
        key: ${{ steps.cachehash.outputs.cachehash }}
        restore-keys: resources_test_

    # sync if need be
    - name: Sync test resources
      run: |
        viash run \
          -p native \
          src/common/sync_test_resources/config.vsh.yaml -- \
          --input $s3_bucket \
          --delete
        tree resources_test/ -L 3

    - name: Build target dir
      run: |
        # allow publishing the target folder
        sed -i '/^target.*/d' .gitignore

        # build target dir
        viash ns build --config_mod ".functionality.version := 'main_build'" --parallel --setup donothing

    - name: Generate schemas
      uses: viash-io/viash-actions/build-nextflow-schemas@v2
      with: 
        token: ${{ secrets.GTHB_PAT }}
        components: src
        workflows: src

    - name: Generate params
      uses: viash-io/viash-actions/build-nextflow-params@v2
      with: 
        token: ${{ secrets.GTHB_PAT }}
        components: src
        workflows: src

    - name: Deploy to target branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: main_build

    - id: ns_list
      uses: viash-io/viash-actions/ns-list@v2
      with:
        platform: docker
        format: json

    - id: set_matrix
      run: |
        matrix_out=$(jq -c ${{ steps.ns_list.outputs.output }} '[ .[] | { "name": (.functionality.namespace + "/" + .functionality.name, "config": .info.config, "dir": .info.config | capture("^(?<dir>.*\/)").dir } ]')
        echo "matrix=matrix_out" >> $GITHUB_OUTPUT

    outputs:
      components_json: ${{ steps.set_matrix.outputs.matrix }}
      cachehash: ${{ steps.cachehash.outputs.cachehash }}

  # phase 2
  build_containers:
    needs: list_components

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list_components.outputs.components_json) }}

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v2

    - name: Build container
      uses: viash-io/viash-actions/ns-build@v2
      with:
        config_mod: .functionality.version := 'main_build'
        setup: build
        src: ${{ matrix.dir }}

    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GTHB_USER }}
        password: ${{ secrets.GTHB_PAT }}

    - name: Push container
      uses: viash-io/viash-actions/ns-build@v2
      with:
        config_mod: .functionality.version := 'main_build'
        setup: push
        platform: docker
        src: ${{ matrix.dir }}