name: viash test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  viash-test:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'main', os: ubuntu-latest }

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        # allow publishing the check_results folder
        sed -i '/^check_results\/$/d' .gitignore 
        
        # run tests and output results to check_results directory
        mkdir check_results
        bin/project_build
        bin/project_test --append=false --log=check_results/results.tsv

    - name: Upload check results
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check_results

