name: viash test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  viash-test:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'main_only_common', os: ubuntu-latest, query: 'common' }
        - {name: 'main_only_MA', os: ubuntu-latest, query: 'modality_alignment' }
        - {name: 'main_only_TI', os: ubuntu-latest, query: 'trajectory_inference' }

    steps:
    - uses: actions/checkout@v2

    - name: Cache executables
      uses: actions/cache@v2
      with:
        path: bin
        key: executable-caching-${{ github.workflow }}-${{ matrix.config.name }}

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Run build
      run: |
        bin/viash_build -q '${{ matrix.config.query }}'

    - name: Run tests
      run: |
        # create check_results folder
        sed -i '/^check_results\/$/d' .gitignore
        mkdir check_results

        # run tests
        bin/viash_test -q '${{ matrix.config.query }}' --append=false --log=check_results/results.tsv

    - name: Upload check results
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check_results

