__inherits__: ../api/comp_split_dataset.yaml
functionality:
  name: "split_datase"
  namespace: "denoising"
  arguments:
    - name: "--method"
      type: "string"
      description: "The process method to assign train/test."
      choices: ["mcv"]
      default: "mcv"
    - name: "--train_frac"
      type: "double"
      description: "The fraction the molecules need to be split to train dataset"
      default: 0.9
    - name: "--seed"
      type: "integer"
      description: "A seed for the subsampling."
      example: 123
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.10"
    setup:
      - type: python
        packages:
          - "anndata>=0.8"
          - numpy
          - scipy
        github:
          - czbiohub/molecular-cross-validation
  - type: nextflow
